/*
 * @file unitTests.H
 *
 * @brief This file is used to include in a single header all teh unit tests 
 *        that have been ported to the GPU.
 *
 * PLEASE REMOVE COMMENTS ONLY WHEN THE KERNEL HAS BEEN PORTED AND TESTED!!!!
 *
 *  @date   18/Giu/2022
 *  @author Mirco Valentini
 */



#ifndef __UNIT_TESTS_IMPLEMENTATION_H__
#define __UNIT_TESTS_IMPLEMENTATION_H__


#include "matVecTestFactory.H"


#endif
